name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: lein test

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run clj-kondo
      run: docker run -v $PWD:/calc --rm cljkondo/clj-kondo clj-kondo --lint /calc

  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: lein run "2 + (5 * 6 + 10)"

